### ISSUE TITLE
对角线遍历

### ISSUE THREAD

**Issue by cymbj666** [datawhalechina/leetcode-notes#326]
有一个题解用的是控制坐标和方向的方法，并且着重提到：**处理边界情况的顺序很重要**，**右边界**和**下边界**的处理必须优先于上边界和左边界，因此虽然左右和上下这两组的处理方法相同但不能合并在一起。我也试过了发现改变处理顺序最后结果是不对的。请问一下这是为什么？
<img width="477" alt="3303dd20c15decffa4dea2bdf3f0fd8" src="https://github.com/datawhalechina/leetcode-notes/assets/167102712/3d898390-8f03-41bc-a630-0437ad0398af">
<img width="532" alt="e8b73dacfa10d3f9c3439f55c79b58c" src="https://github.com/datawhalechina/leetcode-notes/assets/167102712/bc0d93bc-6afa-4d1f-a021-b5b247683b2b">

**Comment by itcharge** [comment]
因为如果走到右上角的位置（图中数字 3 的位置），此处既处于右边界，又处于上边界。如果先判断上边界，则会右移出界。而如果先判断右边界则不会出界。
同理如果处于左下角位置（途中数字 7 的位置），此处既处于左边界，又处于下边界。如果先判断左边界，则会下移出界。而如果先判断下边界则不会出界。
综上所述，应当先判断右边界和下边界，在判断左边界和上边界。
