### ISSUE TITLE
01.04数组二分查找

### ISSUE THREAD

**Issue by STAC2** [datawhalechina/leetcode-notes#327]
![image](https://github.com/datawhalechina/leetcode-notes/assets/67045388/f019119a-6d41-4c31-8a56-34abfa5e8d8e)
这部分查找的元素是6，但是最后却变成了5，是不是错了？

**Comment by itcharge** [comment]
这里确实错了，感谢指正，文中已修复。

> ![image](https://private-user-images.githubusercontent.com/67045388/328173823-f019119a-6d41-4c31-8a56-34abfa5e8d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzA5OTksIm5iZiI6MTcxNTEzMDY5OSwicGF0aCI6Ii82NzA0NTM4OC8zMjgxNzM4MjMtZjAxOTExOWEtNmQ0MS00YzMxLThhNTYtMzRhYmZhNWU4ZDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxMTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YmVjZDlkMDEyMzI0NjgxMDdiZDFlMzMyZDlmNjg2MDZlNzAwNGYyNzhmMDA3MDhmZDJmZjMxZTY0OWM1NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bfl8hAbQSgRkJFKZIVU_EhG7UnJSfmifdFfwhC9gBAk) 这部分查找的元素是6，但是最后却变成了5，是不是错了？

**Comment by STAC2** [comment]
不客气，感谢datawhale！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月8日(星期三) 下午5:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [datawhalechina/leetcode-notes] 01.04数组二分查找 (Issue #327)














 
这里确实错了，感谢指正，文中已修复。
  
 这部分查找的元素是6，但是最后却变成了5，是不是错了？
